name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Download Dependencies
        run: |
          go mod download
          go install github.com/crazy-max/xgo@latest
          docker pull crazymax/xgo:latest

      - name: Build Release
        run: |
          make release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compress
          path: dist/compress

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          files: |
            dist/compress/*
          generate_release_notes: true